name: My First Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: exit 1

  goodbye:
    needs: hello
    runs-on: ubuntu-latest

    steps:
      - name: Say Goodbye
        run: echo "Goodbye!"
