name: My First Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello!"

  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Say Goodbye
        run: echo "Goodbye!"
